[package]
name = "ikill"
version = "1.2.0"
authors = ["pjmp"]
edition = "2018"
keywords = ["cli", "process", "kill", "killall", "fkill"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pjmp/ikill"
repository = "https://github.com/pjmp/ikill"
description = "Interactively kill processes"

[dependencies]
heim = {version = "0.1.0-alpha.1", default-features = false, features = ["process", "runtime-tokio"]}
tokio = { version = "0.2.13", features = ["full", "macros"] }
skim = "0.8.0"
clap = "2.33.0"
